config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  resources :dishes

  root to: 'dishes#index'

  resources :users do
        member do
            get 'register_chef'
            post 'register_chef'
        end
    end

    resources :dishes do
        member do
            get 'purchase'
            post 'purchase'
        end
    end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.role == "chef"
          can :create, :dish
      else
          can :read, :dish
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    end
end

app/models/dish.rb
class Dish < ActiveRecord::Base
    belongs_to :user
    before_save :remove_blanks_from_arrays

    has_attached_file :photo, styles: { :small => "400x400>"}
    validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

    private
    def remove_blanks_from_arrays
        self.ingredients.delete_if &:empty?
        self.category.delete_if {|category| category == ""}
        self.tags.delete_if {|tag| tag == ""}
    end

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
    
end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :dishes

    has_attached_file :photo, styles: { :small => "400x400>", :thumb => "200x200>"}
    validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

    before_save :remove_blanks_from_arrays

    private
    def remove_blanks_from_arrays
        self.ethnicities.delete_if &:empty?
    end

    # enum ethnicities: [ :Mexican, :Italian, :Chinese, :Thai, :American, :French, :Spanish, :Indian, :Japanese ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me, :name, :zip_code, :photo, :ethnicities) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
    end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController

    def index
        @dishes = Dish.all
    end

    def show
        @dish = Dish.find(params[:id])
    end

    def new
        @dish = Dish.new
    end

    def create
        @dish = Dish.create!(dish_params.merge(user_id: current_user.id))
        redirect_to @dish
    end

    def edit
        @dish = Dish.find(params[:id])
    end

    def update
        @dish = Dish.find(params[:id])
        @dish.update(dish_params)
        redirect_to @dish
    end

    def destroy
        @dish = Dish.find(params[:id])
        @dish.destroy
        redirect_to dishes_path
    end

    def purchase

    end

    private
    def dish_params
        params.require(:dish).permit(:name, :photo, {:ingredients => []}, {:tags => []}, {:category => []}, :price, :portion, :quantity, :user_id, :description)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end

    def create
        @user = User.create!(user_params)
        redirect_to @user
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        @user.update(user_params)
        redirect_to @user
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to users_path
    end

    def register_chef
        @user = User.find(params[:id])
    end

    private
    def user_params
        params.require(:user).permit(:name, :zip_code, :photo, {:ethnicities => []}, :role)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chefs/index.html.erb
user index

app/views/dishes/_dish.html.erb
<div class="dish">
    <%= link_to dish_path(dish) do %>
    <h3><%=dish.name%></h3>
    <% end %>
    <%= link_to (image_tag(dish.photo.url)), dish_path(dish) %>
</div>

app/views/dishes/_form.html.erb
<%= form_for @dish, :html => {:multipart => true} do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>
<br>
<%= f.label :photo %>
<%= f.file_field :photo %>
<br>
<%= f.label :ingredients %>
<% 15.times do |n| %>
    <% if @dish.ingredients[n] %>
        <input name="dish[ingredients][]" type="text" value="<%=@dish.ingredients[n]%>"/>
        <% else %>
        <input name="dish[ingredients][]" type="text"/>
    <% end %>
<% end %>
<br>
<%= f.label :tags %>
<% 6.times do |n| %>
<% if @dish.tags[n] %>
    <input name="dish[tags][]" type="text" value="<%=@dish.tags[n]%>"/>
    <% else %>
    <input name="dish[tags][]" type="text"/>
<% end %>
<% end %>
<br>
<%= f.label :category %>
<% 6.times do |n| %>
    <% if @dish.category[n] %>
        <input name="dish[category][]" type="text" value="<%=@dish.category[n]%>"/>
    <% else %>
        <input name="dish[category][]" type="text"/>
    <% end %>
<% end %>
<br>
<%= f.label :price %>
<%= f.text_field :price %>
<br>
<%= f.label :portion %>
<%= f.text_field :portion %>
<br>
<%= f.label :quantity %>
<%= f.text_field :quantity %>
<br>
<%= f.label :description %><br />
<%= f.text_area :description, class:'foodDesc' %>
<br>
  <%= f.submit %>

<% end %>

app/views/dishes/edit.html.erb
<h2 class="pageHeader">Edit your dish   ---   <%= link_to "(delete dish)", dish_path(@dish), method: :delete %></h2>

<p>Here are a few reminders:</p>

<ul>
    <li>Name your dish!</li>
    <ul><li>Creativity is good. But clarity is good, too.</li></ul>
    <li>Take a picture (this is required!) For tips on taking a world-class photo, check <a href="#">here</a>.</li>
    <li>A list of the ingredients you used</li>
    <ul><li>This doesn't have to be comprehensive, but MUST include everything that might cause an allergic reaction!</li>
    <li>For a list of all ingredients you MUST list, check <a href="#">here</a>.</li></ul>
    <li>A price (it's YOUR kitchen--put it to work!)</li>
    <li>A portion size</li>
    <ul><li>This could be "1 taco", "1 plate", or 6oz. WHatever makes sense.</li></ul>
    <li>The quantity you have available (based on your portion sizes)</li>
    <li>Finally, write a quick description! How did you cook it? What ingredients did you focus on? Basically, what makes it DELICIOUS?</li>
</ul>

<%= render 'form' %>

app/views/dishes/index.html.erb
<h2 class="pageHeader">Dishes</h2>

<%= render partial: "dish", collection: @dishes.sort_by{|x| [x.updated_at] }.reverse %>

app/views/dishes/new.html.erb
<h2 class="pageHeader">Share a dish on Chezcasa!</h2>

<p>Want to share your kitchen skillz and feed a hungry neighbor? List your homecooked meals on Chezcasa!</p>
<p>Here's what you'll need to have ready:</p>
<ul>
    <li>Name your dish!</li>
    <ul><li>Creativity is good. But clarity is good, too.</li></ul>
    <li>Take a picture (this is required!) For tips on taking a world-class photo, check <a href="#">here</a>.</li>
    <li>A list of the ingredients you used</li>
    <ul><li>This doesn't have to be comprehensive, but MUST include everything that might cause an allergic reaction!</li>
    <li>For a list of all ingredients you MUST list, check <a href="#">here</a>.</li></ul>
    <li>A price (it's YOUR kitchen--put it to work!)</li>
    <li>A portion size</li>
    <ul><li>This could be "1 taco", "1 plate", or 6oz. WHatever makes sense.</li></ul>
    <li>The quantity you have available (based on your portion sizes)</li>
    <li>Finally, write a quick description! How did you cook it? What ingredients did you focus on? Basically, what makes it DELICIOUS?</li>
</ul>

<%= render 'form' %>

app/views/dishes/purchase.html.erb
<h2 class="pageHeader">purchase dish here</h2>

app/views/dishes/show.html.erb
<h2 class="pageHeader"><%= @dish.name %>!
    <% if @dish.user == current_user %>
    <%= link_to "(edit)", edit_dish_path(@dish) %>
    <% else %>
     - <%= @dish.user.name %>
     <%end%></h2>

<h3>$<%= @dish.price %> for <%= @dish.portion %><% if current_user %> --- <%= link_to "Purchase Now!", purchase_dish_path(@dish) %><%end%></h3>
<h4><%= @dish.quantity %> available!</h4>

<section class="imageAndIngredients">
<%= image_tag(@dish.photo.url, :class => "dishImage") %>

<div class="ingredientsBox">
    <h3>Ingredients:</h3>
    <ul class="ingredientList">
        <% @dish.ingredients.each do |ingredient| %>
            <li><%= ingredient %></li>
        <% end %>
    </ul>
</div>
</section>

<h3>Description</h3>
<p class="description"><%= @dish.description %></p>

<section class="catsAndTags">
    <div class="categoryBox">
        <h4>Categories:</h4>
        <ul class="categories">
            <% @dish.category.each do |category| %>
                <li><%= category %></li>
            <% end %>
        </ul>
    </div>
    <div class="tagBox">
        <h4>Tags:</h4>
        <ul class="tags">
            <% @dish.tags.each do |tag| %>
                <li><%= tag %></li>
            <% end %>
        </ul>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Chezcasa</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/dishes"><%= image_tag "cc_logo.png" %></a>
          <span class="navbar-title">Chezcasa</span>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/dishes">Home</a></li>
            <li><%= link_to "Dishes", dishes_path %></li>
            <% if can? :create, :dish %><li><%= link_to "Post a Dish!", new_dish_path %></li> <% end %>
            <li><%= link_to "Chefs", users_path %></li>
            <% if current_user && current_user.role != "chef" %><li><%= link_to "Register as a Chef!", register_chef_user_path(current_user) %></li> <% end %>
            <% if current_user %><li><%= link_to "My Profile", user_path(current_user) %></li> <% end %>
            <% if !current_user %><li><%= link_to "Sign Up", new_user_registration_path %></li> <% end %>
            <% if !current_user %><li><%= link_to "Log In", new_user_session_path %></li> <% end %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete if current_user %></li>
            <!-- <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li> -->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
          <!-- <ul>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete if current_user %></li>
              <% if !current_user %><li><%= link_to "Log In", new_user_session_path %></li> <% end %>
              <% if !current_user %><li><%= link_to "Sign Up", new_user_registration_path %></li> <% end %>
              <% if current_user %><li><%= link_to "My Profile", user_path(current_user) %></li> <% end %>
              <% if current_user && current_user.role != "chef" %><li><%= link_to "Register as a Chef!", register_chef_user_path(current_user) %></li> <% end %>
              <li><%= link_to "Chefs", users_path %></li>
              <% if can? :create, :dish %><li><%= link_to "Post a Dish!", new_dish_path %></li> <% end %>
              <li><%= link_to "Dishes", dishes_path %></li>
              <li><%= image_tag "cc_logo.png" %></li>
          </ul> -->

<div class="container flashes">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
</div>

<%= yield %>

</body>
</html>

app/views/users/_user.html.erb
<div class="userBox">
    <div class="userNameAndPhoto">
    <h3><%= user.name %> - <%= user.zip_code %></h3>
    <%= image_tag user.photo.url(:thumb) %>
    </div>
    <div class="userCats">
        <h4>Ethnicities Cooked:</h4>
        <ul>
            <% user.dishes.each do |dish| %>
                <% dish.category.each do |cat| %>
                <li><%= cat %></li>
                <% end %>
            <% end %>
        </ul>
    </div>
</div>

app/views/users/edit.html.erb
<h2 class="pageHeader">Edit Profile</h2>

<%= form_for @user, :html => {:multipart => true} do |f| %>
<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>

<div class="field">
  <%= f.label :zip_code %><br />
  <%= f.text_field :zip_code %>
</div>

<div class="field">
  <%= f.label :photo %><br />
  <%= f.file_field :photo %>
</div>

<div class="field">
    <%= f.label :ethnicities %><br />
    <% 6.times do |n| %>
      <% if @user.ethnicities[n] %>
          <input name="user[ethnicities][]" type="text" value="<%=@user.ethnicities[n]%>"/>
      <% else %>
          <input name="user[ethnicities][]" type="text"/>
      <% end %>
    <% end %>
</div>

<div class="actions">
  <%= f.submit "Update" %>
</div>
<% end %>

app/views/users/index.html.erb
<h2 class="pageHeader">Check out the Chezcasa chefs!</h2>

<section class="chefList">
<%= render partial: "user", collection: @users.select{|x| x.role == 'chef' } %>
</section>

app/views/users/new.html.erb
new user

app/views/users/register_chef.html.erb
<h2 class="pageHeader">Would you like to be a chef for Chezcasa?</h2>

<p>Just click Yes below!</p>

<%= form_for @user do |f| %>

<%= f.hidden_field :role, :value=>"chef" %>

<%= f.submit "Yes" %>

<% end %>

app/views/users/show.html.erb
<section class="userShow">
<h2 class="pageHeader"><%= @user.name %>
    <% if current_user == @user %>
     -
     <%= link_to("(edit profile)", edit_user_path(@user)) %>
     <%end%></h2>
<% if @user.dishes != [] %>
<h3>Dishes Offered:</h3>
    <div class="dishesYouCooked">
        <% 5.times do |n| %>
            <% if @user.dishes[n] != nil %>
            <%= link_to dish_path(@user.dishes.sort_by{|x| [x.updated_at] }.reverse[n]) do %>
            <div class="cookedDishBox">
                <h4><%= @user.dishes.sort_by{|x| [x.updated_at] }.reverse[n].name %></h4>
                <%= image_tag @user.dishes.sort_by{|x| [x.updated_at] }.reverse[n].photo.url %>
            </div>
            <% end %>
            <% end %>
        <% end %>
    </div>
    <div class="dishesYouCooked">
        <% 5.times do |n| %>
            <% if @user.dishes[n+5] != nil %>
            <%= link_to dish_path(@user.dishes.sort_by{|x| [x.updated_at] }.reverse[n+5]) do %>
            <div class="cookedDishBox">
                <h4><%= @user.dishes.sort_by{|x| [x.updated_at] }.reverse[n+5].name %></h4>
                <%= image_tag @user.dishes.sort_by{|x| [x.updated_at] }.reverse[n+5].photo.url %>
            </div>
            <% end %>
            <% end %>
        <% end %>
    </div>
<% end %>

<h4>Email:</h4>
<p><%= @user.email %></p>
<p>To edit your email and/or password, click
    <% if current_user == @user %>
    <%= link_to("here", edit_user_registration_path(@user)) %>
    <%end%>
    .</p>

<h4>Zip Code:</h4>
<p><%= @user.zip_code %></p>

<h4>Photo:</h4>
<p><%= image_tag @user.photo.url(:small) %></p>

<h4>Ethnicities:</h4>
<ul>
<% @user.ethnicities.each do |ethnicity| %>
<li><%=ethnicity%></li>
<% end %>
</ul>

<h4>Role:</h4>
<p><%= @user.role %></p>
</section>